---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backup-secret
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: oci/backup
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: oci/backup
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: VAULT_APPROLE_ROLE_ID
    remoteRef:
      key: vault/snapshot
      property: approle_role_id
  - secretKey: VAULT_APPROLE_SECRET_ID
    remoteRef:
      key: vault/snapshot
      property: approle_secret_id
