---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/talos/argocd
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  chart:
    spec:
      chart: argo-cd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      version: 6.7.18
  interval: 1m0s
  values:
    configs:
      cm:
        exec.enabled: "true"
        oidc.config: |
          name: Dex
          issuer: https://dex.gangsterkitties.com/dex
          clientID: argocd
          requestedScopes:
            - openid
            - groups
      params:
        server.insecure: true
      rbac:
        policy.csv: |
          g, admins, role:admin
          g, readonly, role:dev-role
          p, role:dev-role, clusters, get, *, allow
          p, role:dev-role, applications, get, prod/*, allow
          p, role:dev-role, logs, get, prod/*, allow
          p, role:dev-role, exec, create, prod/*, allow
        scopes: '[groups]'
    controller:
      metrics:
        applicationLabels:
          enabled: true
        enabled: true
        serviceMonitor:
          enabled: true
          selector:
            release: kps
    crds:
      install: false
    dex:
      enabled: false
    global:
      domain: argocd.gangsterkitties.com
    notifications:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          selector:
            release: kps
      notifiers:
        service.slack: |
          token: $slack-token
      secret:
        create: false
        name: slack-token
      subscriptions:
      - recipients:
        - slack:alerts
        triggers:
        - on-health-degraded
        - on-sync-failed
        - on-sync-status-unknown
      templates:
        template.app-deployed: |
          email:
            subject: New version of an application {{.app.metadata.name}} is up and running.
          message: |
            {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
          slack:
            attachments: |
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#18be52",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                },
                {
                  "title": "Revision",
                  "value": "{{.app.status.sync.revision}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
        template.app-health-degraded: |
          email:
            subject: Application {{.app.metadata.name}} has degraded.
          message: |
            {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} has degraded.
            Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
          slack:
            attachments: |-
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#f4c030",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
        template.app-sync-failed: |
          email:
            subject: Failed to sync application {{.app.metadata.name}}.
          message: |
            {{if eq .serviceType "slack"}}:exclamation:{{end}}  The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
            Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
          slack:
            attachments: |-
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#E96D76",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
        template.app-sync-running: |
          email:
            subject: Start syncing application {{.app.metadata.name}}.
          message: |
            The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.
            Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
          slack:
            attachments: |-
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#0DADEA",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
        template.app-sync-status-unknown: |
          email:
            subject: Application {{.app.metadata.name}} sync status is 'Unknown'
          message: |
            {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync is 'Unknown'.
            Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
            {{if ne .serviceType "slack"}}
            {{range $c := .app.status.conditions}}
                * {{$c.message}}
            {{end}}
            {{end}}
          slack:
            attachments: |-
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#E96D76",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
        template.app-sync-succeeded: |
          email:
            subject: Application {{.app.metadata.name}} has been successfully synced.
          message: |
            {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
            Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
          slack:
            attachments: |-
              [{
                "title": "{{ .app.metadata.name}}",
                "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": "#18be52",
                "fields": [
                {
                  "title": "Sync Status",
                  "value": "{{.app.status.sync.status}}",
                  "short": true
                },
                {
                  "title": "Repository",
                  "value": "{{.app.spec.source.repoURL}}",
                  "short": true
                }
                {{range $index, $c := .app.status.conditions}}
                {{if not $index}},{{end}}
                {{if $index}},{{end}}
                {
                  "title": "{{$c.type}}",
                  "value": "{{$c.message}}",
                  "short": true
                }
                {{end}}
                ]
              }]
      triggers:
        trigger.on-deployed: |
          - description: Application is synced and healthy. Triggered once per commit.
            oncePer: app.status.sync.revision
            send:
            - app-deployed
            when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
        trigger.on-health-degraded: |
          - description: Application has degraded
            send:
            - app-health-degraded
            when: app.status.health.status == 'Degraded'
        trigger.on-sync-failed: |
          - description: Application syncing has failed
            send:
            - app-sync-failed
            when: app.status.operationState.phase in ['Error', 'Failed']
        trigger.on-sync-running: |
          - description: Application is being synced
            send:
            - app-sync-running
            when: app.status.operationState.phase in ['Running']
        trigger.on-sync-status-unknown: |
          - description: Application status is 'Unknown'
            send:
            - app-sync-status-unknown
            when: app.status.sync.status == 'Unknown'
        trigger.on-sync-succeeded: |
          - description: Application syncing has succeeded
            send:
            - app-sync-succeeded
            when: app.status.operationState.phase in ['Succeeded']
    repoServer:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          selector:
            release: kps
    server:
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        extraTls:
        - hosts:
          - argocd.gangsterkitties.com
          secretName: wildcard
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          selector:
            release: kps
