---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: forgejo
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  driftDetection:
    mode: enabled
  values:
    knownLastVersion: true
    runner:
      config:
        existingInitSecret: forgejo-runner-init
        file:
          runner:
            labels:
              # - kubernetes:docker://docker.io/library/node:lts
              - kubernetes:docker://docker.io/library/docker:29-cli
            envs:
              A_TEST_ENV_NAME_1: null
              A_TEST_ENV_NAME_2: null
              DOCKER_HOST: tcp://127.0.0.1:2376
              DOCKER_TLS_VERIFY: 1
              DOCKER_CERT_PATH: /certs/client
            container:
              network: host
              enable_ipv6: false
              privileged: false
              options: -v /certs/client:/certs/client
              valid_volumes:
                - /certs/client
