---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  data:
  - remoteRef:
      key: gitlab
      property: runner_token
    secretKey: runner-token
