apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: forgejo-runner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          runner:
            file: .runner
            capacity: 1
            labels:
              - kubernetes:docker://docker.io/library/node:lts
          server:
            connections:
              forgejo:
                url: https://git.gangsterkitties.com/
                uuid: "33623933-3563-3366-3465-353633623333"
                token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: forgejo
        property: kubernetes_runner_token
