apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-init
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: forgejo-runner-init
    template:
      engineVersion: v2
      data:
        CONFIG_INSTANCE: https://git.gangsterkitties.com
        CONFIG_NAME: kubernetes
        CONFIG_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: forgejo
        property: runner_registration_token
