---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluxcd-gitlab
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fluxcd-gitlab
  data:
    - secretKey: identity
      remoteRef:
        key: gitlab
        property: fluxcd_private_key
    - secretKey: known_hosts
      remoteRef:
        key: gitlab
        property: known_hosts
