---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
spec:
  address: https://slack.com/api/chat.postMessage
  channel: alerts-info
  secretRef:
    name: slack-bot-token
  type: slack
  username: Flux - fivealive
