---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: flux-operator
  values:
    web:
      config:
        baseURL: https://flux.gangsterkitties.com
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: flux
            clientSecret: flux
            issuerURL: https://dex.gangsterkitties.com/dex
      ingress:
        enabled: true
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
    serviceMonitor:
      create: true
      labels:
        release: kps
