---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: flux-operator
  driftDetection:
    mode: enabled
  values:
    config:
      authentication:
        type: OAuth2
        oauth2:
          provider: OIDC
          clientID: flux
          clientSecret: flux
          issuerURL: https://dex.gangsterkitties.com/dex
    web:
      httpRoute:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: cilium
            sectionName: https
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 256Mi
    serviceMonitor:
      create: true
      labels:
        release: kps
