---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-bot-token
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-bot-token
  data:
    - secretKey: token
      remoteRef:
        key: slack
        property: flux
