---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  chart:
    spec:
      version: "1.19.x"
  values:
    ingressController:
      service:
        annotations:
          metallb.io/loadBalancerIPs: 10.0.102.251
