---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.19.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    defaultLBServiceIPAM: none
    ingressController:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: poptart-ingress.gangsterkitties.com
          lbipam.cilium.io/ips: 10.0.102.252
        loadBalancerClass: io.cilium/l2-announcer
    # hubble:
    #   metrics:
    #     enabled:
    #       - dns:query;ignoreAAAA
    #       - drop
    #       - tcp
    #       - flow
    #       - icmp
    #       - http
    #     serviceMonitor:
    #       enabled: true
    #       labels:
    #         release: kps
    #     dashboards:
    #       enabled: true
    #       annotations:
    #         grafana_folder: Cilium
    #   relay:
    #     enabled: true
    #     prometheus:
    #       enabled: true
    #       serviceMonitor:
    #         enabled: true
    #         labels:
    #           release: kps
    #   ui:
    #     enabled: true
    #     ingress:
    #       enabled: true
    #       annotations:
    #         external-dns.alpha.kubernetes.io/target: poptart-ingress.gangsterkitties.com
    #       hosts:
    #         - poptart-hubble.gangsterkitties.com
    #       tls:
    #         - hosts:
    #             - poptart-hubble.gangsterkitties.com
    # nodePort:
    #   enabled: true
