---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 15m
  values:
    controller:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: poptart-ingress2.gangsterkitties.com
          lbipam.cilium.io/ips: 10.0.102.251
