---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 15m
  values:
    controller:
      ingressClassResource:
        default: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: poptart-ingress2.gangsterkitties.com
          metallb.io/loadBalancerIPs: 10.0.102.251
