---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/infra-stage3/cilium
  - ../../base/infra-stage3/ingress-nginx
  - ./cilium
patches:
  - path: cilium.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: cilium
  - path: ingress-nginx.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx

  ### json patches

  # Cilium gateway service

  - patch: |
      - op: add
        path: /spec/loadBalancerClass
        value: "io.cilium/l2-announcer"
    target:
      kind: Service
      name: cilium-gateway-cilium-gateway
      namespace: cilium
