---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/infra-stage3/cilium
  - ../../base/infra-stage3/ingress-nginx
patches:
  - path: cilium.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: cilium
  - path: ingress-nginx.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
