---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-oci-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-oci-credentials
  dataFrom:
    - extract:
        key: oci/loki
