---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - database.yaml
  - keycloak-temp-admin.yaml
  - podmonitor.yaml
  - postgres-cluster.yaml
  - postgres-keycloak.yaml

