---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-keycloak
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: keycloak
  podMetricsEndpoints:
    - port: metrics
