apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: argocd
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-token
  data:
  - secretKey: slack-token
    remoteRef:
      key: creds/slack
      property: argocd_token
