---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-job.yaml
  - backup-secret.yaml
  - database.yaml
  - namespace.yaml
  - podmonitor.yaml
  - postgres-cluster.yaml
  - postgres-secrets.yaml
