---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fivealive-postgres
  namespace: postgres
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fivealive-postgres
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "postgres"
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      key: cnpg
      property: postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fivealive-dex
  namespace: postgres
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fivealive-dex
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "dex"
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      key: cnpg
      property: dex
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fivealive-registry
  namespace: postgres
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fivealive-registry
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "registry"
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      key: cnpg
      property: registry
