# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: harbor-admin-password
#   namespace: harbor
# spec:
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: harbor-admin-password
#     creationPolicy: Owner
#   data:
#   - secretKey: HARBOR_ADMIN_PASSWORD
#     remoteRef:
#       key: creds/harbor
#       property: HARBOR_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-db-password
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-db-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: cnpg
      property: registry
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-secrets
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oci-secrets
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: oci/harbor
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: oci/harbor
      property: AWS_SECRET_ACCESS_KEY
