---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  dependsOn:
    - name: kps-crds
      namespace: monitoring
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.12.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  driftDetection:
    mode: enabled
  values:
    networkPolicies:
      restrictInternalTraffic: false
    persistence:
      defaultDiskSelector:
        enable: true
        selector: "nvme"
      defaultNodeSelector:
        enable: true
        selector: "storage"
    preUpgradeChecker:
      jobEnabled: false
    defaultSettings:
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: 10
      storageReservedPercentageForDefaultDisk: 0
      storageOverProvisioningPercentage: 200
    longhornUI:
      replicas: 1
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kps
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: storage.k8s.io/v1
              kind: StorageClass
              name: longhorn
            patch: |-
              - op: replace
                path: /parameters/numberOfReplicas
                value: 2
