apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-ldap
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: BIND_PASS
    remoteRef:
      key: ldap
      property: readonly
  target:
    name: grafana-ldap
    template:
      type: Opaque
      data:
        ldap-toml: |
          [[servers]]
          host = "ldap.gangsterkitties.com"
          port = 636
          use_ssl = true
          start_tls = false
          ssl_skip_verify = false
          bind_dn = "cn=readonly,ou=services,dc=gangsterkitties,dc=com"
          bind_password = "{{ .BIND_PASS }}"
          search_filter = "(uid=%s)"
          search_base_dns = ["ou=people,dc=gangsterkitties,dc=com"]
          group_search_filter = "(&(objectClass=posixGroup)(member=%s))"
          group_search_base_dns = ["ou=groups,dc=gangsterkitties,dc=com"]
          group_search_filter_user_attribute = "dn"

          [servers.attributes]
          # member_of = "memberOf"
          email =  "mail"

          [[servers.group_mappings]]
          group_dn = "cn=admins,ou=groups,dc=gangsterkitties,dc=com"
          org_role = "Admin"
          grafana_admin = true
