---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kps
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  driftDetection:
    mode: enabled
  install:
    crds: Skip
  values:
    nameOverride: kps
    crds:
      enabled: false
    alertmanager:
      config:
        route:
          receiver: 'null'
          routes:
            - matchers:
                - alertname = "InfoInhibitor"
              receiver: 'null'
            - matchers:
                - alertname = "KubeMemoryOvercommit"
              receiver: 'null'
            - matchers:
                - alertname = "NodeMemoryHighUtilization"
                - severity = "warning"
              receiver: 'null'
            - matchers:
                - alertname = "Watchdog"
              receiver: 'null'
        receivers:
          - name: 'null'
          - name: 'slack'
            slack_configs:
              - channel: alerts
                api_url: https://slack.com/api/chat.postMessage
                http_config:
                  authorization:
                    credentials_file: /etc/alertmanager/secrets/slack-token/slack-token
                send_resolved: true
                title: '{{ template "slack.title" . }}'
                text: '{{ template "slack.text" . }}'
                color: '{{ template "slack.color" . }}'
                actions:
                  - type: button
                    text: 'Runbook :green_book:'
                    url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
                  - type: button
                    text: 'Query :mag:'
                    url: '{{ (index .Alerts 0).GeneratorURL }}'
                  - type: button
                    text: 'Dashboard :chart_with_upwards_trend:'
                    url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
                  - type: button
                    text: 'Silence :no_bell:'
                    url: '{{ template "__alert_silence_link" . }}'
      ingress:
        enabled: true
        paths:
          - /
        pathType: Prefix
      alertmanagerSpec:
        secrets:
          - slack-token
    grafana:
      deploymentStrategy:
        type: Recreate
      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password
      defaultDashboardsEnabled: false
      ingress:
        enabled: true
        path: /
      grafana.ini:
        auth.anonymous:
          enabled: true
        auth.ldap:
          enabled: true
          config_file: /etc/grafana/ldap.toml
      ldap:
        enabled: true
        existingSecret: grafana-ldap
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: grafana-dashboards-kubernetes
              orgId: 1
              folder: "Kubernetes"
              type: file
              disableDeletion: true
              editable: false
              options:
                path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
        grafana-dashboards-kubernetes:
          k8s-addons-prometheus:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-addons-prometheus.json
            token: ''
          k8s-system-api-server:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
            token: ''
          k8s-system-coredns:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
            token: ''
          k8s-views-global:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
            token: ''
          k8s-views-namespaces:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
            token: ''
          k8s-views-nodes:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
            token: ''
          k8s-views-pods:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
            token: ''
    prometheus:
      ingress:
        enabled: true
        paths:
          - /
        pathType: Prefix
