---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 168h  # Check for updates every 7 days
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    semver: ">= 1.0.0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
