---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rfc2136-keys
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rfc2136-keys
    template:
      data:
        rfc2136-tsig-keyname: external-dns
        rfc2136-tsig-secret: "{{ .rfc2136TsigSecret }}"
  data:
    - secretKey: rfc2136TsigSecret
      remoteRef:
        key: synology
        property: external_dns_key
