---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kps-grafana
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-984c8a14-bb66-4fb5-808d-e1b460e55323
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kps-prometheus-db-prometheus-kps-prometheus-0
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-bd1c6f7e-d676-454d-b662-d4eff6f65644
