---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  dependsOn:
    - name: kps-crds
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: ">= 0.1.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    prometheus:
      serviceAccount: kps-prometheus
      namespace: monitoring
      serviceMonitor:
        enabled: true
        speaker:
          additionalLabels:
            release: kps
        controller:
          additionalLabels:
            release: kps
    speaker:
      frr:
        enabled: false
