---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 15m
  values:
    httpRoute:
      annotations:
        external-dns.alpha.kubernetes.io/target: poptart-ingress.gangsterkitties.com
      hostnames:
        - host: poptart-headlamp.gangsterkitties.com
