---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/external-secrets
  - ../base/flux
  - ../base/headlamp
  - ../base/kps
  - ./external-secrets
  - ./flux
patches:
  - path: external-secrets.yaml
    target:
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
  - path: flux.yaml
    target:
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
  - path: headlamp.yaml
    target:
      kind: HelmRelease
      name: headlamp
      namespace: kube-system
  - path: kps.yaml
    target:
      kind: HelmRelease
      name: kps
      namespace: monitoring

  ### json patches

  # FluxInstance sync path

  - patch: |
      - op: replace
        path: /spec/sync/path
        value: "clusters/poptart"
    target:
      kind: FluxInstance
      name: flux
      namespace: flux-system

  # Flux Slack alert username
  - patch: |
      - op: replace
        path: /spec/username
        value: "Flux - poptart"
    target:
      kind: Provider
      name: slack-bot
      namespace: flux-system
