---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 15m
  values:
    httproute:
      enabled: true
      parentRefs:
        - name: cilium-gateway
          namespace: cilium
          sectionName: https
      hostnames:
        - longhorn.gangsterkitties.com
