---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
    - 10.0.101.252/32  # ingress-nginx
    - 10.0.101.253/32  # cilium-gateway
    - 10.0.101.254/32  # cilium-ingress
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
spec:
  ipAddressPools:
    - default-pool
