---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: fivealive
  namespace: postgres
spec:
  schedule: "0 0 11 * * *"
  backupOwnerReference: self
  cluster:
    name: fivealive
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
