---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: test
      property: foo
