---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 15m
  values:
    global:
      domain: argocd.gangsterkitties.com
    controller:
      resources:
        limits:
          memory: 768Mi
        requests:
          memory: 768Mi
    server:
      resources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
      httproute:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: cilium
            sectionName: https
        hostnames:
          - argocd.gangsterkitties.com
      grpcroute:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: cilium
            sectionName: https
        hostnames:
          - argocd-grpc.gangsterkitties.com
        rules:
          - matches:
              - headers:
                  - name: Content-Type
                    type: RegularExpression
                    value: "^application/grpc.*$"
    repoServer:
      resources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
