apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: atlantis
spec:
  interval: 15m
  values:
    atlantisUrl: https://atlantis.gangsterkitties.com
    orgAllowlist: git.gangsterkitties.com/aaron/terraform
    gitea:
      user: atlantis
      baseUrl: https://git.gangsterkitties.com
    vcsSecretName: atlantis-vcs
    repoConfig: |
      ---
      repos:
      - id: git.gangsterkitties.com/aaron/terraform
        apply_requirements: [mergeable]
        workflow: default
        allowed_overrides: []
        allow_custom_workflows: false
      workflows:
        default:
          plan:
            steps: [init, plan]
          apply:
            steps: [apply]
      metrics:
        prometheus:
          endpoint: /metrics
    route:
      main:
        enabled: true
        hostnames:
          - atlantis.gangsterkitties.com
        parentRefs:
          - name: cilium-gateway
            namespace: cilium
            sectionName: https
    volumeClaim:
      storageClassName: longhorn
    loadEnvFromSecrets:
      - aws-credentials
  # postRenderers:
  #   - kustomize:
  #       patches:
  #         - target:
  #             version: monitoring.coreos.com/v1
  #             kind: ServiceMonitor
  #             name: atlantis
  #           patch: |
  #             - op: replace
  #               path: /metadata/labels/release
  #               value: kps
