apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 15m
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: dex-config
    ingress:
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: fivealive-ingress2.gangsterkitties.com
      hosts:
        - host: dex.gangsterkitties.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - dex.gangsterkitties.com
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 32Mi
