---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: fluent-bit
      version: "0.58.x"
      sourceRef:
        kind: HelmRepository
        name: fluent
  driftDetection:
    mode: enabled
  values:
    image:
      repository: git.gangsterkitties.com/gangsterkitties/images/fluent-bit
      tag: 5.1.1-rpi16k
    serviceMonitor:
      enabled: true
      selector:
        release: kps
    dashboards:
      enabled: true
    extraPorts:
      - port: 5170
        containerPort: 5170
        protocol: TCP
        name: tcp
    ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
    config:
      service: |
        [SERVICE]
            Daemon        Off
            Flush         {{ .Values.flush }}
            Log_Level     {{ .Values.logLevel }}
            Parsers_File  /fluent-bit/etc/parsers.conf
            Parsers_File  /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_Port     {{ .Values.metricsPort }}
            Health_Check  On

      ## https://docs.fluentbit.io/manual/pipeline/inputs
      inputs: |
        [INPUT]
            Name              tail
            Path              /var/log/containers/*.log
            multiline.parser  docker, cri
            Tag               kube.*
            Mem_Buf_Limit     5MB
            Skip_Long_Lines   On

        [INPUT]
            Name    tcp
            Listen  0.0.0.0
            Port    5170
            Format  json
            Tag     talos.*

      ## https://docs.fluentbit.io/manual/pipeline/filters
      filters: |
        [FILTER]
            Name                 kubernetes
            Match                kube.*
            Merge_Log            On
            Keep_Log             Off
            K8S-Logging.Parser   On
            K8S-Logging.Exclude  On

        [FILTER]
            Name    modify
            Match   talos.*
            Rename  talos-service  talos_service
            Rename  talos-level    talos_level

      ## https://docs.fluentbit.io/manual/pipeline/outputs
      outputs: |
        [OUTPUT]
            Name                    loki
            Match                   kube.*
            Host                    loki-gateway
            Port                    80
            tenant_id               1
            Labels                  job=fluent-bit
            Auto_Kubernetes_Labels  on

        [OUTPUT]
            Name        loki
            Match       talos.*
            Host        loki-gateway
            Port        80
            tenant_id   1
            Labels      job=talos,talos_server=$server,talos_service=$talos_service,talos_level=$talos_level

      ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
      ## This configuration is deprecated, please use `extraFiles` instead.
      upstream: {}

      ## https://docs.fluentbit.io/manual/pipeline/parsers
      customParsers: |
