---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 15m
  values:
    web:
      config:
        baseURL: https://flux.gangsterkitties.com
      networkPolicy:
        create: false
      httpRoute:
        annotations:
          external-dns.alpha.kubernetes.io/target: fivealive-gateway.gangsterkitties.com
        hostnames:
          - host: flux.gangsterkitties.com
