---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dex
  - ../base/external-secrets
  - ../base/flux
  - ../base/headlamp
  - ../base/kps
  - ./dex
  - ./external-secrets
  - ./flux
  - ./kps
  - ./talos-etcd
patches:
  - path: dex.yaml
    target:
      kind: HelmRelease
      name: dex
      namespace: dex
  - path: external-secrets.yaml
    target:
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
  - path: flux.yaml
    target:
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
  - path: headlamp.yaml
    target:
      kind: HelmRelease
      name: headlamp
      namespace: kube-system
  - path: kps.yaml
    target:
      kind: HelmRelease
      name: kps
      namespace: monitoring
