---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources: []
resources:
  - ./flux
#   - ../base/podinfo
patches:
  - path: flux.yaml
    target:
      kind: HelmRelease
#   - path: podinfo.yaml
