---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux
  - ./kps
  - ./talos-etcd
  # - ../base/grafana
  - ../base/headlamp
patches:
  - path: flux.yaml
    target:
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
  - path: headlamp.yaml
    target:
      kind: HelmRelease
      name: headlamp
      namespace: kube-system
  - path: kps.yaml
    target:
      kind: HelmRelease
      name: kps
      namespace: monitoring
