---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      version: 6.9.1
  values:
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/target: podinfo.gangsterkitties.com
      hosts:
        - host: podinfo.gangsterkitties.com
          paths:
            - path: /
              pathType: Prefix
