---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 15m
  values:
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 64Mi
