---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-config
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oci-config
  dataFrom:
    - extract:
        remoteRef:
          key: oci/atlantis
