---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.19.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    resources:
      limits:
        memory: 384Mi
      requests:
        memory: 384Mi
    ingressController:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: fivealive-ingress.gangsterkitties.com
          lbipam.cilium.io/ips: 10.0.101.254
    envoy:
      resources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
    operator:
      resources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
