---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/infra-stage3/cilium
  - ../../base/infra-stage3/external-dns
  - ../../base/infra-stage3/traefik
  - ./cilium
patches:

  ### helm release overrides

  - path: cilium.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: cilium
  - path: external-dns.yaml
    target:
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
  - path: traefik.yaml
    target:
      kind: HelmRelease
      name: traefik
      namespace: traefik

  ### json patches

  # Cilium gateway hostname annotation

  - patch: |
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: "fivealive-gateway.gangsterkitties.com"
    target:
      kind: Gateway
      name: cilium-gateway
      namespace: cilium

  # Cilium gateway IP address

  - patch: |
      - op: replace
        path: /spec/infrastructure/annotations/lbipam.cilium.io~1ips
        value: "10.0.101.253"
    target:
      kind: Gateway
      name: cilium-gateway
      namespace: cilium
