---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  values:
    ingressRoute:
      dashboard:
        annotations:
          external-dns.alpha.kubernetes.io/target: fivealive-ingress3.gangsterkitties.com
        matchRule: Host(`fivealive-traefik.gangsterkitties.com`)
    logs:
      access:
        enabled: false  # disabled by default - set this to true to enable
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: fivealive-ingress3.gangsterkitties.com
        lbipam.cilium.io/ips: 10.0.101.251
