---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 15m
  values:
    # logLevel: debug
    sources:
      # - gateway-grpcroute
      # - gateway-httproute
      - ingress
      - service
    txtOwnerId: poptart
