---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/infra-stage1/cert-manager
  - ../../base/infra-stage1/external-dns
  - ../../base/infra-stage1/gateway-api
  - ../../base/infra-stage1/kps-crds
  - ../../base/infra-stage1/metallb
  - ./kps
patches:
  - path: cert-manager.yaml
    target:
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  - path: external-dns.yaml
    target:
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
  - path: metallb.yaml
    target:
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
