---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - cidr: 10.0.102.250/32  # traefik
    - cidr: 10.0.102.251/32  # ingress-nginx
    - cidr: 10.0.102.252/32  # cilium-ingress
    - cidr: 10.0.102.253/32  # cilium-gateway
