---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/infra-stage2/cert-manager
  - ../../base/infra-stage2/k8s-admins.yaml
  - ./kps
  # - ./metallb
patches:
  - patch: |
      - op: replace
        path: /spec/acme/server
        value: https://acme-staging-v02.api.letsencrypt.org/directory
    target:
      kind: ClusterIssuer
      name: letsencrypt
      namespace: cert-manager
