apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: atlantis
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: atlantis
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: atlantis
  values:
    defaultTFDistribution: opentofu
    service:
      type: ClusterIP
    ingress:
      enabled: false
    environment:
      TOFU_PLUGIN_CACHE_DIR: "/atlantis-data/tofu-plugin-cache"
    initContainers:
      - name: init-plugin-cache
        image: alpine:latest
        command: ["mkdir", "-p", "/atlantis-data/tofu-plugin-cache"]
        volumeMounts:
          - name: atlantis-data
            mountPath: /atlantis-data
    servicemonitor:
      enabled: true
